version: 2.1

jobs:
  echo:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Greet
          command: sleep 10
          no_output_timeout: 3s

workflows:
  main:
    jobs:
      - echo
